version: "2"
exclude_patterns:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.jpg"
  - "**/*.pdf"
  - "**/*.png"
  - "packages/interface/gatsby-*"
  - "packages/interface/src/utils/api.tsx"
