version: "2"
exclude_patterns:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.jpg"
  - "**/*.pdf"
  - "**/*.png"
  - "packages/delete-your-data/gatsby-*"
  - "packages/justice-for-rickie-slaughter/gatsby-*"
  - "packages/law-job-resources/gatsby-*"
  - "packages/neon-law/gatsby-*"
  - "packages/shared-ui/src/utils/api.tsx"
