version: "2"
exclude_patterns:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.jpg"
  - "**/*.pdf"
  - "**/*.png"
  - "web/src/utils/api.tsx"
  - "web/cypress/**/*"
  - "server/tests/utils/**/*"
