---
version: "3.8"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_DB: neon_law
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    restart: unless-stopped
    logging:
      driver: none

  logic:
    image: neonlaw/logic
    container_name: logic
    restart: unless-stopped
    ports:
      - 3000:3000
    logging:
      driver: none
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/neon_law
      - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      - AUTH0_TENANT=neon-law-testing
      - NODE_ENV=production
      - SHOW_GRAPHIQL=true
