---
version: "3.8"

x-shared-variables: &shared-variables
  - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
  - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
  - AUTH0_TENANT=neon-law-testing.auth0.com
  - DATABASE_URL=postgres://postgres:password@postgres:5432/neon_law
  - GOOGLE_APPLICATION_CREDENTIALS=credentials.json
  - NODE_ENV=development
  - SHOW_GRAPHIQL=true
  - CYPRESS_AUTH_URL=$CYPRESS_AUTH_URL
  - CYPRESS_AUDIENCE_URL=$CYPRESS_AUDIENCE_URL
  - CYPRESS_AUTH_CLIENT_ID=$CYPRESS_AUTH_CLIENT_ID
  - CYPRESS_AUTH_CLIENT_SECRET=$CYPRESS_AUTH_CLIENT_SECRET

x-javascript-volumes: &javascript-volumes
  - ./:/app
  - node_modules:/app/node_modules
  - ./yarn.lock:/app/yarn.lock:ro

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neon_law
    restart: unless-stopped
    logging:
      driver: none

  api:
    build:
      context: ./
      dockerfile: ./docker/api.Dockerfile
    restart: always
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - shell
    environment: *shared-variables
    volumes: *javascript-volumes

  interface:
    build:
      context: ./
      dockerfile: ./docker/development.interface.Dockerfile
    container_name: interface
    restart: always
    depends_on:
      - api
    ports:
      - 8000:8000
    volumes: *javascript-volumes
    environment:
      PACKAGE_NAME: interface

  law_job_resources:
    build:
      context: ./
      dockerfile: ./docker/development.interface.Dockerfile
    restart: always
    container_name: law_job_resources
    depends_on:
      - api
    ports:
      - 5000:8000
    volumes: *javascript-volumes
    environment:
      PACKAGE_NAME: law-job-resources

  justice_for_rickie_slaughter:
    build:
      context: ./
      dockerfile: ./docker/development.interface.Dockerfile
    restart: always
    container_name: justice_for_rickie_slaughter
    depends_on:
      - api
    ports:
      - 7000:8000
    volumes: *javascript-volumes
    environment:
      PACKAGE_NAME: justice-for-rickie-slaughter

  delete_your_data:
    build:
      context: ./
      dockerfile: ./docker/development.interface.Dockerfile
    restart: always
    container_name: delete_your_data
    depends_on:
      - api
    ports:
      - 6000:8000
    volumes: *javascript-volumes
    environment:
      PACKAGE_NAME: delete-your-data

  language-tool:
    image: silviof/docker-languagetool
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 8001:8010

  shell:
    build:
      context: ./
      dockerfile: ./docker/shell.Dockerfile
    container_name: shell
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment: *shared-variables
    restart: unless-stopped

volumes:
  node_modules:
