source "https://rubygems.org"

# Specify your gem's dependencies in neon_postgres.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "standard"

gem "pry", "~> 0.14.1"

gem "faker", "~> 2.17"

gem "meilisearch", "~> 0.15.3"
