source "https://rubygems.org"

# Specify your gem's dependencies in neon_postgres_tests.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "standard"

gem "sequel", "~> 5.43"
gem "fixture_dependencies", "~> 1.10"
gem "pg", "~> 1.2"
