/* eslint-disable max-len */

export const questions = [
  'How can you impeaching a witness?',
  'How can you create an easement?',
  'How is a joint tenancy severed?',
  'What are the differences between CA and federal civil procedure?',
  'What is required to seek the remedy of reformation after making a unilateral mistake?',
  'What are the tested criminal elements of the Fifth Amendment?',
  'What are the tested criminal elements of the Eighth Amendment?',
  'What is service of process?',
  'What is the exclusionary rule?',
  'What is strict products liability?',
  'What is a motion to compel?',
  'What is the work product privilege of objecting to discovery requests?',
  'What is strict liability?',
  'What is the attorney-client privilege?',
  'How can a party assert the defense of unclean hands?',
  'What is a fee simple defeasible?',
  'What are the tested joint ownership topics?',
  'What are the tested evidence privileges?',
  'What is partial integration of a contract?',
  'What is collateral estoppel?',
  'What is the parol evidence rule?',
  'What are the elements of a contract?',
  'What are the tested topics of breach of contract?',
  'How can a client sue an attorney for attorney malpractice?',
  'What are the tested types of business associations?',
  'What are the big picture topics for crimes?',
  'What are the standards of review for constitutional law cases?',
  'What are the elements of the "Statute of Frauds"?',
  'How is joint tenancy considered community property?',
  'What are real covenants for real property?',
  'What is the harmless error rule as it relates to the exclusionary rule?',
  'What are reliance damages?',
  'What are the tested freehold estates?',
  'What are the duties of an owner of an easement?',
  'What is relevance?',
  'What is a California general partnership?',
  'What constitutes "extreme and outrageous conduct" for IIED?',
  'What are the tested criminal elements of the Sixth Amendment?',
  'What are the elements of murder?',
  'What is the dormant commerce clause?',
  'What are the tested crimes against a person?',
  'What is the takings clause?',
  'What are the diversity of citizenship requirements for a federal case?',
  'What is a conveyance of real property?',
  'What is rational basis review?',
  'What is the business judgment rule?',
  'What is the "Best Evidence Rule"?',
  'What are the requirements of a shareholder to inspect company records?',
  'What is a valid prenuptial agreement?',
  'What is the free exercise clause of the 1st amendment?',
  'What are the warranties of a seller in a real estate contract?',
  'What are interrogatories in discovery?',
  'What are punitive damages?',
  'What is character evidence?',
  'What is intestate succession?',
  'What is separate property?',
  'What is the plain view exception to a search without a warrant?',
  'What are the tested intentional torts?',
  'What is a defective product?',
  'What are the requirements to bring a derivative suit?',
  'What are the tested terms of a contract?',
  'What a lawyer\'s duties to avoid a conflict of interest?',
  'What are the tested questions about documents in evidence?',
  'What is misrepresentation?',
  'What are character evidence exceptions in criminal court?',
  'probable cause',
  'What is ademption by extinction?',
  'How can a party revoke a will?',
  'How do you admit a document in a case?',
  'What is an attorney\'s duty of candor?',
  'What are the big picture topics for real property?',
  'How is community property defined in California?',
  'What is a business de jure?',
  'How does a court consider a claim to have proper ripeness?',
  'What is promissory estoppel?',
  'What are the elements of tortious nuisance?',
  'What are the types of tested post-trial motions?',
  'What are the duties of a lawyer representing a corporation?',
  'What are the damages for defamation?',
  'What are the tested means of acquiring property?',
  'What are the conditions on revocable trusts when made inter vivos?',
  'How can a party seek specific performance of a contract?',
  'What is hearsay?',
  'How is malice defined as it relates to murder?',
  'What is probable cause?',
  'What is the joint tenancy unity of possession?',
  'What are the tested topics of jurisdiction?',
  'What is the remedy of specific performance?',
  'What is constructive eviction?',
  'What are the tested defenses to a formation of a contract?',
  'What is the race-notice statute?',
  'What is an easement by necessity?',
  'What is the merger doctrine?',
  'What does complete integration of a contract mean?',
  'What are the elements of fraud?',
  'Impeaching a Witness for Truthfulness',
  'What are the elements of tortious assault?',
  'How can a party assert the defense of mutual mistake?',
  'What are the elements of first-degree murder?',
  'What are incidental damages?',
  'What is a privilege log?',
  'What is the commerce clause?',
  'What is an attractive nuisance?',
  'What does proper venue mean?',
  'How do you object to Questions of a Witness',
  'What are the specific acts character evidence exceptions?',
  'How must the police conduct phono lineups?',
  'What is a "time is of the essence" clause?',
  'What are the 12 hearsay exceptions?',
  'What is appurtenant easement?',
  'What are the subjects on the bar exam?',
  'What are a business directors duties of loyalty?',
  'What is the scope of discovery?',
  'What is lay witness testimony?',
  'What are the elements of defamation?',
  'What are the elements of tortious battery?',
  'What is reformation?',
  'What is a partition of property for a tenancy in common?',
  'What is the Privileges and Immunities Clause?',
  'What does "concerning the moving party" mean in a defamation claim?',
  'What are the tested public policy exclusions?',
  'What is a joinder of claims?',
  'What is the eleventh amendment?',
  'What is the defense of insanity?',
  'What is an attorney\'s duty to safeguard?',
  'What is the consumer expectation test?',
  'What must an attorney do after withdrawing from a client?',
  'What is recission?',
  'What is the transmutation of community property?',
  'What are the big picture topics for torts?',
  'What are the big picture topics for constitutional law?',
  'What is the business records exception to hearsay?',
  'What is "slander per se"?',
  'What is attorney\'s duty to report for corporate clients?',
  'What is the medical examinations privilege?',
  'What is quasi-community property in California?',
  'What is an attorney\'s duty to avoid frivilous claims?',
  'What is a long arm statute?',
  'What are the tested terms of gift distribution?',
  'What are the elements of IIED?',
  'What are the elements of kidnapping?',
  'What is the shelter rule for bona-fide purchasers?',
  'What are the elements of burglary?',
  'What is the need to meet and confer?',
  'How can a party defend themselves from an intentional tort with the defense of consent?',
  'What are the elements of negligent infliction of emotional distress?',
  'What is the joint tenancy unity of time?',
  'What are the big picture topics for professional responsibility?',
  'What are the elements of adverse possession?',
  'How can a party assert the defense of laches?',
  'What are the elements of false imprisonment?',
  'What is the merchant confirmation memo?',
  'What are valid searches and seizures?',
  'What are the tested criminal elements of the Fourth Amendment?',
  'What is required for the disclosure of experts?',
  'How can a court fill in void provisions?',
  'What are the tested elements of justiciability?',
  'What is a joint tenancy?',
  'What are the powers of a board in a corporation?',
  'What is a defamatory statement?',
  'What is intermediate scrutiny?',
  'What are the tested incomplete crimes?',
  'What is the defense of defense of property?',
  'What are the elements of trespass to chattel and conversion?',
  'What are nominal damages?',
  'Defense of Qualified Privilege to Defamation',
  'What is the burden of production?',
  'What is the subsequent remedial measures public policy exception?',
  'What is a material breach of contract?',
  'What does "matters of public concern" mean in a defamation claim?',
  'What are the tested crimes of theft?',
  'What are the tested shareholder rights topics for business associations?',
  'What are the elements of trespass to land?',
  'What is res judicata?',
  'What is replivin?',
  'How must California attorneys handle written fee agreements?',
  'What  are equitable servitudes?',
  'What are the big picture topics for remedies?',
  'What are the elements of defamation of a public person?',
  'What is anticipatory repudiation?',
  'What is the rule on the discoverability of investigative reports?',
  'What are the big picture topics for evidence?',
  'What are the differences between an offer and an advertisement?',
  'When will a court consider severing a criminal case?',
  'What test is used to determine the validity of a regulation of symbolic speech?',
  'What is a foreseeable plaintiff?',
  'What is a valid real property contract?',
  'What are the big picture topics for business associations?',
  'What rights do the Fourth Amendment guarantee?',
  'What is judicial notice?',
  'How are conflicts imputed on a new firm in CA?',
  'What are the tested restrictions on property topics?',
  'How can a party rehabilitate a previously impeached witness?',
  'How can a party answering an interrogatory?',
  'What are zoning regulations?',
  'What are the elements of involuntary manslaughter?',
  'What is the applicable law for the sale of goods?',
  'What is a temporary restraining order?',
  'What is habit and custom evidence?',
  'How can a party defend themselves from an intentional tort with self-defense?',
  'What is the pro-rata share rule for communiyt property?',
  'What does quasi-community property mean?',
  'How can a party adequately object to discovery requests?',
  'What are the tested landlord tenant issues?',
  'What is the standard from US v. Katz?',
  'What is a valid will?',
  'What are the UCC rules for merchants?',
  'What are the tested pre-trial motions?',
  'What is the defense of entrapment?',
  'How does California handle Divorce and Community Property?',
  'What are the big picture topics for civil procedure?',
  'What are the elements of a criminal conspiracy?',
  'How can a party assert the defense of others?',
  'What are the elements of voluntary manslaughter?',
  'What is strict scrutiny?',
  'What is the burden of production in producing evidence?',
  'What is a preliminary injunction?',
  'What is the joint tenancy unity of interest?',
  'What are the exceptions to statute of frauds?',
  'What are the types of discovery motions?',
  'What are the big picture topics for wills and trusts?',
  'What are the character evidence exceptions in civil court?',
  'What does "plain meaning" mean when a court analyzes a contract?',
  'How can a party assert the defense of recission?',
  'What are the rules surrounding written production?',
  'What are the elements of robbery?',
  'What is an easement in gross?',
  'What does a reasonable expectation of privacy mean?',
  'How can a court determine the validity of a regulation about the Establishment Clause?',
  'What are the tested elements of constitutional federal powers?',
  'When must an attorney withdraw from representing a client?',
  'What are the tested defenses to defamation?',
  'What happens to community property after a permanent separation?',
  'What is the balancing test a court uses for Due Process?',
  'How is Community Property defined in California?',
  'What is the joint tenancy unity of title?',
  'How can a party assert the contract breach defense of "Duty to Mitigate"?',
  'How are goods defined according the UCC?',
  'What is the Pinkerton liability of co-conspirators?',
  'What are the requirements for federal court standing?',
  'What is required for an attorney to permissively withdraw from representing a client?',
  'How can a party remove a case to federal court?',
  'What are the elements of negligence?',
  'What are the rights of creditors in obtaining trust property?',
  'What is the dying declaration exception to hearsay?',
  'What is a tenancy in common?',
  'What are the tested subjects of witnesses?',
  'What are the authentication requirements for documents?',
  'What are the big picture topics for contracts?',
  'What is the good faith exception to a warrantless search?',
  'What are the big picture topics for community property?',
  'What is the Right to Remain Silent?',
  'What are the duties of a landlord?',
  'What is declatory relief?',
  'What is federal subject matter jurisdiction?',
  'What is federal court jurisdiction?',
  'What is larceny?',
  'What is an attorney\'s duty to report unethical behavior?',
  'burglary',
  'How can you request the production of documents?',
  'What is the spousal privilege of testimony?',
  'What is personal jurisdiction?',
];
