source "https://rubygems.org"

# Specify your gem's dependencies in webhooks.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

gem "roda", "~> 3.44"

gem "rack", "~> 2.2"

gem "webrick", "~> 1.7"

gem "standardrb", "~> 1.0"
