---
name: continuous_integration

on:
  push:
    branches:
      - development
      - production
  pull_request:
    branches:
      - development

jobs:
  test_suite:
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.LOGIC_AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.LOGIC_AUTH0_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Dependencies.
        run: yarn install --ignore-optional
      - name: Run Linting.
        run: yarn lint
      - name: Run TypeScript Type Checking.
        run: yarn check-types
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.5.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn test
      - name: Run Yarn Build.
        run: yarn build
        working-directory: ./packages/neon-law
        env:
          GATSBY_ACTIVE_ENV: staging
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: docker-compose -f cypress-docker-compose.yml up
          wait-on: "http://127.0.0.1:8000"
          wait-on-timeout: 1200
          working-directory: ./packages/neon-law
        env:
          CYPRESS_AUTH_URL: ${{ secrets.CYPRESS_AUTH_URL }}
          CYPRESS_AUTH_CLIENT_ID: ${{ secrets.CYPRESS_AUTH_CLIENT_ID }}
          CYPRESS_AUTH_CLIENT_SECRET: ${{ secrets.CYPRESS_AUTH_CLIENT_SECRET }}
          CYPRESS_PORTAL_USER_PASSWORD: ${{ secrets.CYPRESS_PORTAL_USER_PASSWORD }}
      - name: Ensure latest autogenerated graphql-codegen code is up-to-date
        run: |
          yarn graphql-codegen
          git diff --exit-code
