---
name: development

on:
  push:
    branches:
      - development

jobs:
  deploy_development_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the development Docker image
        run: |-
          docker build \
            --tag "neonlaw/interface:latest" \
            --build-arg GATSBY_ACTIVE_ENV=development \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            -f Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: http://127.0.0.1:8000/callback/
          GATSBY_AUTH0_DOMAIN: neon-law-testing.auth0.com
          GATSBY_AUTH0_CLIENT_ID: http://127.0.0.1:3000/graphql

      - name: Authenticate to the Docker Hub
        run: |-
          docker login \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} \
            -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push neonlaw/interface
