---
name: docker_hub

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy_base_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |-
          docker build \
            --tag "neonlaw/base:latest" \
            -f ./docker/base.Dockerfile \
            .

      - name: Authenticate to the Docker Hub
        run: |-
          docker login \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} \
            -p ${{ secrets.DOCKER_HUB_TOKEN }}
        if: github.ref == '/refs/heads/flashcards'

      - name: Push Image to Docker Hub
        run: docker push neonlaw/base
        if: github.ref == '/refs/heads/flashcards'
