---
name: documents_release

on:
  release:
    types:
      - published

jobs:
  update_neon_documents_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/documents@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Build neon_documents gem
        run: gem build neon_documents.gemspec
        working-directory: ./documents
      - name: Publish neon_documents gem to Rubygems
        run: gem push neon_documents-$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/documents@/,"")}1').gem
        working-directory: ./documents
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-staging
          service_account_email: github-actions@neon-law-staging.iam.gserviceaccount.com
          service_account_key: ${{ secrets.STAGING_GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Upload zip file to GCP Storage
        run: |
          zip documents.zip -r documents/*
          gsutil cp gs://neon-law-staging-function-code/documents/$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/documents@/,"")}1').zip emails.zip

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Upload zip file to GCP Production
        run: |
          zip documents.zip -r documents/*
          gsutil cp gs://neon-law-production-function-code/documents/$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/documents@/,"")}1').zip emails.zip
