---
name: git_flow_release

on:
  release:
    types:
      - published

jobs:
  update_git_flow_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/git_flow@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Login to Crates
        run: cargo login $CRATES_API_KEY
        env:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}

      - name: Publish Git Flow
        run: cargo publish
        working-directory: ./git_flow
