---
name: git_flow_for_prs

on:
  pull_request:
    branches:
      - main

jobs:
  validate_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Validate pull request.
        working-directory: ./git_flow
        run: |
          cargo run -- \
            validate-pull-request \
              --head-ref ${GITHUB_HEAD_REF#refs/heads/} \
              --base-ref ${GITHUB_BASE_REF#refs/heads/} \
              --pr-number ${{github.event.number}}
        env:
          DOPPLER_TOKEN: ${{ secrets.GITHUB_PAT }}
