---
name: neon_nlp_release

on:
  release:
    types:
      - published

jobs:
  update_neon_nlp_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/neon_nlp@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Login to Crates
        run: cargo login $CRATES_API_KEY
        env:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/neon_nlp@')

      - name: Publish Neon NLP
        run: cargo publish
        if: startsWith(github.ref, 'refs/tags/neon_nlp@')
        working-directory: ./neon_nlp
