---
name: operations_release

on:
  release:
    types:
      - published

jobs:
  update_neon_operations_ruby_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/operations@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Build neon_operations gem
        run: gem build neon_operations.gemspec
        working-directory: ./operations
      - name: Publish neon_operations gem to Rubygems
        run: gem push neon_operations-$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/operations@/,"")}1').gem
        working-directory: ./operations
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
