---
name: postgres_release

on:
  release:
    types:
      - published

jobs:
  update_neon_postgres_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/neon_postgres@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Build neon_postgres gem
        run: gem build neon_postgres.gemspec
        working-directory: ./postgres
      - name: Publish neon_postgres gem
        run: gem push neon_postgres-$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/neon_postgres@/,"")}1').gem
        working-directory: ./postgres
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
