---
name: production

on:
  push:
    branches:
      - production

jobs:
  deploy_neon_law_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/interface:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/interface:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=neon-law \
            -f Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/interface:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/interface:latest"

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment interface \
             interface=us.gcr.io/neon-law-production/interface:$GITHUB_SHA

  deploy_law_job_resources_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/law-job-resources:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=law-job-resources \
            -f Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/law-job-resources:latest"

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment law-job-resources \
             law-job-resources=us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA

  deploy_justice_for_rickie_slaughter_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=justice-for-rickie-slaughter \
            -f Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:latest"

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment justice-for-rickie-slaughter \
             justice-for-rickie-slaughter=us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA

  deploy_delete_your_data_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/delete-your-data:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/delete-your-data:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=delete-your-data \
            -f Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/delete-your-data:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/delete-your-data:latest"

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment delete-your-data \
             delete-your-data=us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA
