---
name: production

on:
  pull_request:
    branches:
      - development

  # Deploy production from development at 4:00 am PST, Monday through Thursday
  schedule:
    - cron: "0 12 * * 1-4"

  workflow_dispatch:

jobs:
  deploy_interface_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/interface:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/interface:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_AUTH0_TENANT=auth.neonlaw.com \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=interface \
            --build-arg DOMAIN_NAME=www.neonlaw.com \
            -f docker/production.interface.Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/interface:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/interface:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment interface \
            interface=us.gcr.io/neon-law-production/interface:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'

  deploy_law_job_resources_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/law-job-resources:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_AUTH0_TENANT=auth.neonlaw.com \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg DOMAIN_NAME=www.lawjobresources.com \
            --build-arg APP_NAME=law-job-resources \
            -f docker/production.interface.Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/law-job-resources:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment law-job-resources \
            law-job-resources=us.gcr.io/neon-law-production/law-job-resources:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'

  deploy_justice_for_rickie_slaughter_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_AUTH0_TENANT=auth.neonlaw.com \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=justice-for-rickie-slaughter \
            --build-arg DOMAIN_NAME=www.justiceforrickieslaughter.com \
            -f docker/production.interface.Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}
        if: github.ref == 'refs/heads/development'

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/justice-for-rickie-slaughter:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment justice-for-rickie-slaughter \
            justice-for-rickie-slaughter=us.gcr.io/neon-law-production/justice-for-rickie-slaughter:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'

  deploy_delete_your_data_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/delete-your-data:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/delete-your-data:latest" \
            --build-arg GATSBY_AUTH0_CALLBACK="$GATSBY_AUTH0_CALLBACK" \
            --build-arg GATSBY_AUTH0_DOMAIN="$GATSBY_AUTH0_DOMAIN" \
            --build-arg GATSBY_AUTH0_CLIENT_ID="$GATSBY_AUTH0_CLIENT_ID" \
            --build-arg GATSBY_AUTH0_TENANT=auth.neonlaw.com \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg APP_NAME=delete-your-data \
            --build-arg DOMAIN_NAME=www.deleteyourdata.com \
            -f docker/production.interface.Dockerfile \
            .
        env:
          GATSBY_AUTH0_CALLBACK: ${{ secrets.PRODUCTION_AUTH0_CALLBACK }}
          GATSBY_AUTH0_DOMAIN: ${{ secrets.PRODUCTION_AUTH0_DOMAIN }}
          GATSBY_AUTH0_CLIENT_ID: ${{ secrets.PRODUCTION_AUTH0_CLIENT_ID }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/delete-your-data:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/delete-your-data:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment delete-your-data \
            delete-your-data=us.gcr.io/neon-law-production/delete-your-data:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'

  deploy_production_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/api:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/api:latest" \
            -f docker/api.Dockerfile \
            .
        if: github.ref == 'refs/heads/development'

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/api:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/api:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment production-api \
             production-api=us.gcr.io/neon-law-production/api:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'
