---
name: production

on:
  pull_request:
    branches:
      - development

  # Deploy production from development at 2:00 am PST every day
  schedule:
    - cron: "0 10 * * *"

  workflow_dispatch:

jobs:
  deploy_production_interface:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/interface:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/interface:latest" \
            --build-arg GATSBY_ACTIVE_ENV=production \
            --build-arg DOMAIN_NAME=www.neonlaw.com \
            --build-arg APP_NAME=web \
            -f docker/production.interface.Dockerfile \
            .

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/interface:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/interface:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law-production --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment production-interface \
            interface=us.gcr.io/neon-law-production/interface:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'

  deploy_production_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "us.gcr.io/neon-law-production/server:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-production/server:latest" \
            -f ./server/Dockerfile \
            .

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_email: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
        if: github.ref == 'refs/heads/development'

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker
        if: github.ref == 'refs/heads/development'

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-production/server:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-production/server:latest"
        if: github.ref == 'refs/heads/development'

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials neon-law-production --region us-west4
        if: github.ref == 'refs/heads/development'

      - name: Update the base image
        run: |-
          kubectl set image deployment production-api \
             api=us.gcr.io/neon-law-production/server:$GITHUB_SHA

          kubectl set image deployment production-workers \
             workers=us.gcr.io/neon-law-production/server:$GITHUB_SHA
        if: github.ref == 'refs/heads/development'
