---
name: python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python_diagram_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3'
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install dependencies
        working-directory: ./diagrams
        run: poetry install
      - name: Lint Python files.
        working-directory: ./diagrams
        run: poetry run black --check
      - name: Check that the diagrams are the latest
        working-directory: ./diagrams
        run: |
          poetry run python -m neon_diagrams.web_diagram
          poetry run python -m neon_diagrams.gcp_diagram
          poetry run python -m neon_diagrams.k8s_diagram
          poetry run python -m neon_diagrams.kafka_diagram
          git diff -G. --exit-code .
