---
name: releases

on:
  release:
    types:
      - published

jobs:
  update_git_flow_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Login to Crates
        run: cargo login $CRATES_API_KEY
        env:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/git_flow@')

      - name: Publish Git Flow
        run: cd ./git_flow && cargo publish
        if: startsWith(github.ref, 'refs/tags/git_flow@')

  update_i18n_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Publish @neonlaw/i18n
        run: cd ./i18n && npm publish --access public
        if: startsWith(github.ref, 'refs/tags/i18n@')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  update_neon_nlp_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Login to Crates
        run: cargo login $CRATES_API_KEY
        env:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/neon_nlp@')

      - name: Publish Neon NLP
        run: cd ./neon_nlp && cargo publish
        if: startsWith(github.ref, 'refs/tags/neon_nlp@')

  update_web_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Publish @neonlaw/web
        run: cd ./web && npm publish --access public
        if: startsWith(github.ref, 'refs/tags/web@')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        if: startsWith(github.ref, 'refs/tags/web@')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./web
