---
name: releases

on:
  release:
    - created

jobs:
  update_git_flow_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Crates
        run: cargo login $CRATES_API_KEY
        with:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/git_flow@')

      - name: Publish Git Flow
        run: cd ./git_flow && cargo publish
        if: startsWith(github.ref, 'refs/tags/git_flow@')
