---
name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruby_postgres_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./postgres
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./postgres
        run: bundle exec standardrb

  ruby_emails_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./emails
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./emails
        run: bundle exec standardrb

  ruby_documents_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./documents
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./documents
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./documents
        run: bundle exec rspec spec

  ruby_schemas_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./schemas
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./schemas
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./schemas
        run: bundle exec rspec spec

  ruby_secrets_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./secrets
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./secrets
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./secrets
        run: bundle exec rspec spec
