---
name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruby_postgres_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./postgres
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./postgres
        run: bundle exec standardrb

  ruby_emails_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./emails
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./emails
        run: bundle exec standardrb
      - name: Run specs
        working-directory: ./emails
        run: bundle exec rspec spec

  ruby_documents_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./documents
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./documents
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./documents
        run: bundle exec rspec spec

  ruby_schemas_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./schemas
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./schemas
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./schemas
        run: bundle exec rspec spec

  ruby_secrets_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Secrets Files
        id: secrets-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            secrets/*
            secrets/**
            secrets/**/*
      - name: Install dependencies
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: yarn install --frozen-lockfile
      - name: Install dependencies
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle exec rspec spec

  ruby_webhooks_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./webhooks
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./webhooks
        run: bundle exec standardrb

  ruby_search_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./search
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./search
        run: bundle exec standardrb
