---
name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruby_postgres_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./postgres
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./postgres
        run: bundle exec standardrb

  ruby_email_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./email
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./email
        run: bundle exec standardrb
