---
name: ruby

on:
  pull_request:
    branches:
      - main

jobs:
  ruby_postgres_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./postgres
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./postgres
        run: bundle exec standardrb

  ruby_emails_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./emails
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./emails
        run: bundle exec standardrb
      - name: Run specs
        working-directory: ./emails
        run: bundle exec rspec spec

  ruby_documents_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./documents
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./documents
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./documents
        run: bundle exec rspec spec

  ruby_schemas_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Install dependencies
        working-directory: ./schemas
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./schemas
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./schemas
        run: bundle exec rspec spec
        env:
          CODE_CLIMATE_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}


  ruby_secrets_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Secrets Files
        id: secrets-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            secrets/*
            secrets/**
            secrets/**/*
      - name: Install dependencies
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: yarn install --frozen-lockfile
      - name: Install dependencies
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./secrets
        if: steps.secrets-files.outputs.any_changed == 'true'
        run: bundle exec rspec spec

  ruby_webhooks_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Webhooks Files
        id: webhooks-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            webhooks/*
            webhooks/**
            webhooks/**/*
      - name: Install dependencies
        working-directory: ./webhooks
        if: steps.webhooks-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./webhooks
        if: steps.webhooks-files.outputs.any_changed == 'true'
        run: bundle exec standardrb

  ruby_search_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Search Files
        id: search-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            search/*
            search/**
            search/**/*
      - name: Install dependencies
        working-directory: ./search
        if: steps.search-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./search
        if: steps.search-files.outputs.any_changed == 'true'
        run: bundle exec standardrb

  ruby_slack_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Slack Files
        id: slack-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            slack/*
            slack/**
            slack/**/*
      - name: Install dependencies
        working-directory: ./slack
        if: steps.slack-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./slack
        if: steps.slack-files.outputs.any_changed == 'true'
        run: bundle exec standardrb

  ruby_operations_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - name: Changed Operations Files
        id: slack-files
        uses: tj-actions/changed-files@v7
        with:
          files: |
            operations/*
            operations/**
            operations/**/*
      - name: Install dependencies
        working-directory: ./operations
        if: steps.operations-files.outputs.any_changed == 'true'
        run: bundle
      - name: Lint Ruby files.
        working-directory: ./operations
        if: steps.operations-files.outputs.any_changed == 'true'
        run: bundle exec standardrb
      - name: Run RSpec
        working-directory: ./operations
        if: steps.operations-files.outputs.any_changed == 'true'
        run: bundle exec rspec spec
