---
name: search_release

on:
  release:
    types:
      - published

jobs:
  update_neon_search_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/search@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Build neon_search gem
        run: gem build neon_search.gemspec
        working-directory: ./search
      - name: Publish neon_search gem to Ruby Gems
        run: gem push neon_search-$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/search@/,"")}1').gem
        working-directory: ./search
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

      - name: Create Zip file for search
        run: cd search && zip -r ../search.zip *

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-staging
          service_account_search: github-actions@neon-law-staging.iam.gserviceaccount.com
          service_account_key: ${{ secrets.STAGING_GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Upload zip file to GCP Staging
        run: gsutil cp search.zip gs://neon-law-staging-function-code/search/$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/search@/,"")}1').zip

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: neon-law-production
          service_account_search: github-actions@neon-law-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.PRODUCTION_GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Upload zip file to GCP Production
        run: gsutil cp search.zip gs://neon-law-production-function-code/search/$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/search@/,"")}1').zip
