---
name: secrets_release

on:
  release:
    types:
      - published

jobs:
  update_neon_secrets_ruby_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/secrets@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Build neon_secrets gem
        run: gem build neon_secrets.gemspec
        working-directory: ./secrets
      - name: Publish neon_secrets gem to Rubygems
        run: gem push neon_secrets-$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/secrets@/,"")}1').gem
        working-directory: ./secrets
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
