---
name: server_release

on:
  release:
    types:
      - published

jobs:
  update_server_package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/server@')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Login to NPM
        run: npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Publish @neonlaw/server
        run: npm publish --access public
        working-directory: ./server

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "ghcr.io/neonlaw/codebase/server:$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/server@/,"")}1')" \
            -f ./server/Dockerfile \
            .

      - name: Push the Docker image to GitHub Registry
        run: docker push ghcr.io/neonlaw/codebase/server:$(echo $GITHUB_REF | awk '{gsub(/^refs\/tags\/server@/,"")}1')
