---
name: staging

on:
  push:
    branches:
      - develop

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: neon-law-development
          service_account_email: github-actions@neon-law-development.iam.gserviceaccount.com
          service_account_key: ${{ secrets.STAGING_GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: |-
          Configure Docker to use the gcloud command-line tool as a credential
          helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |-
          echo ${{ secrets.STAGING_HTPASSWD }} > staging_htpasswd
          docker build \
            --tag "us.gcr.io/neon-law-development/interface:$GITHUB_SHA" \
            --tag "us.gcr.io/neon-law-development/interface:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg GATSBY_ACTIVE_ENV=staging \
            -f staging.Dockerfile \
            .

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "us.gcr.io/neon-law-development/interface:$GITHUB_SHA"
          docker push "us.gcr.io/neon-law-development/interface:latest"

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |-
          gcloud container clusters get-credentials staging --region us-west4

      - name: Deploy latest container with kubectl
        run: |-
          kubectl set image deployment interface \
             interface=us.gcr.io/neon-law-development/interface:$GITHUB_SHA
