---
name: system_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  system_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GIT_USERNAME }}
      #     password: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
      # - name: Pull Docker images
      #   run: docker-compose pull
      #   env:
      #     DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEVELOPMENT }}
      # - name: Can start Docker Compose
      #   run: docker-compose up -d
