---
name: continuous_integration

on:
  pull_request:

jobs:
  validate_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Git Flow
        run: cargo install git_flow
      - name: Validate Branch
        run: git_flow validate-branch ${GITHUB_HEAD_REF#refs/heads/}
