---
name: yaml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yaml_linting_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3'
      - name: Install Yamllint
        run: pip install --user yamllint
